### ISSUE TITLE
Restructure Phases

### ISSUE THREAD

**Issue by RyanRHall** [stanams/CodeHunt#2]
Probably the biggest piece of feedback I have for you:

Organize your phases **by feature** and not by front end/back end/styling.
Let's do something along the lines of phase1: auth, phase 2: products, phase 3: votes... you get the idea!

**Comment by stanams** [comment]
I've refactored a bit the phases following your advices and it looks way clearer to my mind now! Thanks!
I'll detail each phase accordingly tonight. Let me know if you think the implementation timeline still needs to be improved.
Thanks!

**Comment by stanams** [comment]
Do you want me to simplify the wireframes to be closer to the mvp ?
